

prefix: "&8[&bAOTChatMod&8] &r"




anti-links:
  enabled: true

  detect-obfuscated: true
  # Domaines toujours autorisés
  whitelist:
    - "discord.gg/aotsmp"

  message: "&cLes liens ne sont pas autorisés sur le  serveur !"


anti-spam:
  enabled: true

  max-messages: 2
  time-window: 5
  # Pourcentage de similarité
  similarity-threshold: 85

  cooldown: 800
  message: "&cVeuillez ne pas spammer le chat !"


anti-caps:
  enabled: true

  max-caps-percentage: 20

  min-length: 8

  message: "&cMerci de ne pas écrire en majuscules !"


anti-colors:
  enabled: true
  message: "&cVous n'avez pas la permission d'utiliser les couleurs dans le chat !"


anti-swear:
  enabled: true
  message: "&cMerci de respecter les autres joueurs !"
  notify-staff: true
  staff-notify-permission: "aotchatmod.admin"
  detect-bypass: true



logging:
  enabled: true


messages:
  no-permission: "&cVous n'avez pas la permission d'effectuer cette action."
  player-not-found: "&cJoueur introuvable : &e{player}"
  reload-success: "&aConfiguration rechargée avec succès !"
  mute-success: "&aLe joueur &e{player} &aa été réduit au silence."
  mute-permanent: "&aLe joueur &e{player} &aa été réduit au silence indéfiniment."
  unmute-success: "&aLe joueur &e{player} &an'est plus réduit au silence."
  player-not-muted: "&cCe joueur n'est pas réduit au silence."
  mute-notify: "&cVous avez été réduit au silence par &e{staff}&c. Raison : &f{reason}&c. Durée : &f{duration}&c."
  mute-notify-permanent: "&cVous avez été réduit au silence par &e{staff}&c. Raison : &f{reason}&c. Durée : &findéfinie&c."
  unmute-notify: "&aVotre réduction au silence a été levée par &e{staff}&a."
